apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-iismato
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: m.nemcek@investinslovakia.eu
    privateKeySecretRef:
      name: letsencrypt-iismato
    solvers:
    - http01:
        ingress:
          class: traefik
