apiVersion: v2
name: traefik
description: Traefik ingress controller configuration
type: application
version: 0.1.0
dependencies:
  - name: traefik
    version: 24.0.0
    repository: https://traefik.github.io/charts