apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoapp-production
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/iismato/iac-test.git
        revision: argoapp
        directories:
          - path: charts-2-apps/argoapp
  template:
    metadata:
      name: argoapp-production
      annotations:
        argocd-image-updater.argoproj.io/image-list: image=registry.digitalocean.com/ktest1/dir:argoapp-v1.13
        argocd-image-updater.argoproj.io/image.update-strategy: digest
        argocd-image-updater.argoproj.io/image.allow-tags: regexp:^argoapp-v[0-9]+\.[0-9]+$
        argocd-image-updater.argoproj.io/argoapp.platform: linux/amd64
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: charts-2-apps/argoapp
        repoURL: https://github.com/iismato/iac-test.git
        targetRevision: argoapp
        helm:
          releaseName: argoapp-production
          valueFiles:
            - values.yaml
            - env-values-production.yaml
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argoapp-production