apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoapp-production
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - scmProvider:
              github:
                # Organizácia alebo užívateľ na GitHube
                organization: investinslovakia
                # Token pre autentifikáciu
                tokenRef:
                  secretName: github-api-token-secret
                  key: token
                allBranches: true
              filters:
                - repositoryMatch: argo-web
                - branchMatch: main
              requeueAfterSeconds: 30
          - git:
              repoURL: https://github.com/iismato/iac-test.git
              revision: main
              directories:
                - path: charts-2-apps/argoapp
  template:
    metadata:
      name: argoapp-production
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd-image-updater.argoproj.io/image-list: image=registry.digitalocean.com/ktest1/dir:argoapp-latest
        argocd-image-updater.argoproj.io/image.update-strategy: digest
        argocd-image-updater.argoproj.io/image.allow-tags: regexp:argoapp-latest
        argocd-image-updater.argoproj.io/argoapp.platform: linux/amd64
        argocd-image-updater.argoproj.io/write-back-method: git
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
      source:
        path: charts-2-apps/argoapp
        repoURL: https://github.com/iismato/iac-test.git
        targetRevision: main
        helm:
          releaseName: argoapp-production
          valueFiles:
            - values.yaml
            - env-values-production.yaml
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argoapp-production
      ignoreDifferences:
        - group: cilium.io
          kind: CiliumIdentity
          jsonPointers:
            - /metadata/managedFields
            - /metadata/resourceVersion
            - /metadata/uid