apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoapp-production
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/iismato/iac-test.git
        revision: argoapp
        directories:
          - path: charts-2-apps/argoapp
  template:
    metadata:
      name: argoapp-production
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: charts-2-apps/argoapp
        repoURL: https://github.com/iismato/iac-test.git
        targetRevision: argoapp
        helm:
          releaseName: argoapp-production
          valueFiles:
            - values.yaml
            - env-values-production.yaml
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argoapp-production