apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - type: git
      url: https://github.com/iismato/argo-web.git
      usernameSecret:
        name: repo-secret
        key: username
      passwordSecret:
        name: repo-secret
        key: password