apiVersion: v1
kind: ConfigMap
metadata:
  name: image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: registry.digitalocean.com
      prefix: registry.digitalocean.com
      api_url: https://registry.digitalocean.com
      credentials: secret:argocd/do-registry-secret#.dockerconfigjson
  log.level: debug  # zmena na debug
  argocd-image-updater.config: |
    interval: 1m
    registries:
      - name: registry.digitalocean.com
        default: true